### ISSUE TITLE
Empty instance name does not allow re-initialization

### ISSUE THREAD

**Issue by falstaff84** [libusbgx/libusbgx#19]
Creating a mass storage function using an empty instance name e.g. by calling `usbg_create_function(g_ms, USBG_F_MASS_STORAGE, "", &f_ms_attrs, &f_ms)` seems to work fine and allow to use the gadget device.

However, trying then to reinitialize the configuration using `usbg_ret = usbg_init("/sys/kernel/config", &s);` fails with -3 `USBG_ERROR_INVALID_PARAM`.

One obvious work-around is to use a non-empty instance name.

**Comment by kopasiak** [comment]
Hmmm... Generally empty instance name should illegal from kernel point of view at least because of functionfs (it's quite hard to mount a device with "" name). So  I'll send kernel patch to fix this and if upstream accepts it I'll also disallow this in libusbgx

**Comment by falstaff84** [comment]
I see, seems reasonable.
