### ISSUE TITLE
Header usbg/function/hid.h not installed

### ISSUE THREAD

**Issue by Saiberion** [libusbgx/libusbgx#7]
The header file usbg/function/hid.h is missing from installation.

When HID functionality was added the source file was added to src/Makefile.am but the header file was forgotten in Makefile.am

**Comment by kopasiak** [comment]
Hi,

thank you very much for catching this. Could you please check if #8 works for you?

**Comment by Saiberion** [comment]
Yes this should work. In my case I only made the changes to Makefile.am to get a working version for my buildroot environment.

**Comment by kopasiak** [comment]
Fix merged. Thank you for reporting this issue.
