### ISSUE TITLE
Are you missing USBG_F_UAC2 ?

### ISSUE THREAD

**Issue by Pillar1989** [libusbgx/libusbgx#9]
Hi 
I  didnt find USBG_F_UAC2 in usbg.h. are you missing it ? or you didnt support it yet.
https://github.com/libusbgx/libusbgx/blob/master/include/usbg/usbg.h#L178-L195

**Comment by kopasiak** [comment]
It's not supported yet but feel free to add the support;) patches are always welcomed

**Comment by kopasiak** [comment]
Support for UAC2 function has been merged.
